POST http://localhost:807/collateral/save
Content-Type: application/json

{
  "type": "airplane",
  "brand": "Aerobus",
  "model": "A300",
  "manufacturer": "Euro",
  "year": 2020,
  "fuelCapacity": 33,
  "seats": 200,
  "values": [{
      "value": "2300000001",
      "date": "2019-08-22T06:11:00.000Z"}]
}

###